version: "3"

services:
  expense-tracker:
    container_name: ExpenseTrackerFrontend
    # The name of the image that will be created when building this container
    image: expense-tracker
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Berlin
    # Points to a file with the sensitive environment variables
    restart: unless-stopped
    ports:
      - 80:3000
